from bias_scope.prompts_based.demographic_representation_bias import DemographicRepresentationBias
from bias_scope.prompts_based.tof_nof import TofNof
from bias_scope.prompts_based.analogical_reasoning_bias import AnalogicalReasoningBias
