#!/usr/bin/env python3
"""Render docs/fidelity/INDEX.md (PLAN.md 4.1).

The verdict for each metric comes from `MetricInfo.fidelity` — what the library
actually reports — not from parsing prose out of the notes. `tests/test_metadata.py`
already pins `MetricInfo.fidelity` to `sources/SOURCES.yaml`, so the chain is:

    sources read  ->  SOURCES.yaml status  ->  MetricInfo.fidelity  ->  this table

with a test at the second arrow and this script at the third. A note is a link,
not a source of truth, which also lets one note cover several metrics that share
a paper.

Exits non-zero if any metric's evidence is inconsistent.

    python scripts/verification/render_fidelity_index.py
"""

from __future__ import annotations

import sys
from collections import Counter
from pathlib import Path
from typing import Dict, List

import yaml

REPO_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO_ROOT / "src"))

NOTES_DIR = REPO_ROOT / "docs" / "fidelity"
MANIFEST = REPO_ROOT / "sources" / "SOURCES.yaml"
OUTPUT = NOTES_DIR / "INDEX.md"

ORDER = ("faithful", "adaptation", "original", "mismatch", "unaudited")

BLURBS = {
    "faithful": "same formula, same protocol; any difference is a documented "
                "access-mode necessity that does not change the statistic",
    "adaptation": "same underlying comparison, different access mode or scoring "
                  "path that *can* change numbers",
    "original": "BiasScope's own operationalization, inspired by a cited idea; "
                "does not carry the cited paper's metric name",
    "mismatch": "implements a different statistic under the cited name — "
                "**must be fixed before release**",
    "unaudited": "sources not yet read, so **no fidelity claim is made**; "
                 "PLAN.md Section 4.0 forbids assigning a status before reading "
                 "the paper and the reference code",
}


def manifest_entries() -> Dict[str, dict]:
    text = MANIFEST.read_text()
    document = yaml.safe_load("metrics:" + text.partition("metrics:")[2])
    return {e["metric"]: e for e in document["metrics"]}


def check(name: str, info, entry) -> List[str]:
    """Consistency between a metric's declared fidelity and its evidence."""
    if entry is None:
        return [f"{name}: no sources/SOURCES.yaml entry"]

    problems: List[str] = []
    read = entry.get("status") == "read"
    if read and info.fidelity == "unaudited":
        problems.append(f"{name}: marked `read` but still `unaudited`")
    if not read and info.fidelity != "unaudited":
        problems.append(f"{name}: claims `{info.fidelity}` but its sources are `pending`")
    if info.fidelity != "unaudited":
        if not info.fidelity_note:
            problems.append(f"{name}: audited but records no fidelity note")
        elif not (REPO_ROOT / info.fidelity_note).exists():
            problems.append(f"{name}: fidelity_note {info.fidelity_note} is missing")
    return problems


def main() -> int:
    from bias_scope._metric_info import METRIC_INFO

    entries = manifest_entries()
    problems: List[str] = [
        problem
        for name, info in sorted(METRIC_INFO.items())
        for problem in check(name, info, entries.get(name))
    ]

    counts = Counter(info.fidelity for info in METRIC_INFO.values())
    total = len(METRIC_INFO)
    read_count = sum(1 for e in entries.values() if e.get("status") == "read")

    body = [
        "# Fidelity index",
        "",
        "Generated by `scripts/verification/render_fidelity_index.py`. Do not edit by hand.",
        "",
        "Each metric's status comes from `MetricInfo.fidelity`, which",
        "`tests/test_metadata.py` pins to its `sources/SOURCES.yaml` status — so a",
        "metric cannot claim a fidelity its sources do not support, and cannot stay",
        "`unaudited` once they have been read.",
        "",
        "## Statuses",
        "",
        *[f"- **{s}** — {BLURBS[s]}." for s in ORDER],
        "",
        "## Progress",
        "",
        f"- Metrics in the library: **{total}**",
        f"- Sources read: **{read_count} / {total}**",
        "",
        "| Status | Count |",
        "|---|---|",
        *[f"| {s} | {counts.get(s, 0)} |" for s in ORDER],
        f"| **total** | **{total}** |",
        "",
    ]

    if counts.get("mismatch"):
        body += [
            f"> **{counts['mismatch']} mismatch(es) outstanding.** PLAN.md Section 13",
            "> requires zero before v0.2.0.",
            "",
        ]

    body += ["## Metrics", "", "| Metric | Family | Status | Note |", "|---|---|---|---|"]
    for name, info in sorted(
        METRIC_INFO.items(), key=lambda kv: (ORDER.index(kv[1].fidelity), kv[0])
    ):
        note = (
            f"[{Path(info.fidelity_note).name}]({Path(info.fidelity_note).name})"
            if info.fidelity_note
            else "—"
        )
        body += [f"| `{name}` | {info.family} | **{info.fidelity}** | {note} |"]
    body.append("")

    OUTPUT.write_text("\n".join(body))
    summary = ", ".join(f"{s} {counts.get(s, 0)}" for s in ORDER)
    print(f"wrote {OUTPUT.relative_to(REPO_ROOT)}: {summary}")

    for problem in problems:
        print(f"  - {problem}")
    return 1 if problems else 0


if __name__ == "__main__":
    sys.exit(main())
